[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dig4bio"
version = "0.1.0"
description = "Utilities and modelling code for the Dig4Bio Kaggle project."
requires-python = ">=3.12"
dependencies = [
    "scipy",
    "matplotlib",
    "notebook",
    "pandas",
    "numpy"
]

[project.scripts]
dig4bio-clean-transfer = "dig4bio.cli:make_interim_transfer_plate_command"
dig4bio-clean-test = "dig4bio.cli:make_interim_test_samples_command"
dig4bio-clean-sources = "dig4bio.cli:make_interim_source_devices_command"
dig4bio-clean-all = "dig4bio.cli:make_all_interim_command"
dig4bio-make-eda = "dig4bio.cli:make_all_eda_figures_command"